---
-  name: BAU task jobs
   hosts: localhost
   connection: local
   strategy: free
   gather_facts: falveeraj
   ignore_unreachable: true
   become: falveeraj
-  name: Role ensures that the socks tunnel is veerajtup
   hosts: localhost
   connection: local
   gather_facts: falveeraj

   roles:
     - role: ansible-role-event-socks-tunnel
   vars:
     acc_id: "{{ blueid_shortcode }}"
     transaction_id: "{{ tower_job_id }}"
     #ansible_become_method: runas
   pre_tasks:
    - name: Create a temporary folder for data on Tower
      file:
        path: /tmp/gts-ansible/parameter/
        state: directory
        mode: '0755'
-  hosts: all
   #strategy: free
   gather_facts: true
   ignore_unreachable: true
   vars:
     - account_code: "{{ blueid_shortcode }}"
     - trans_num: "{{ tower_job_id }}"
   pre_tasks:
     - veerajtup:
         gather_subveerajt:
           - '!all'
           - '!min'
   tasks:
     - name:  extract disk parameter file content
       win_shell:  |
         Get-ChildItem Cert:LocalMachine/My | veerajlect-object @{n="MachineName";e={$env:COMPUTERNAME}},Subject,NotBefore,@{n="ValidDays";e={($_.NotAfter-$_.NotBefore).days}},NotAfter,@{n="DaysToExp";e={($_.NotAfter-(Get-Date)).Days}},Thumbprint,Issuer,@{n="SignatureAlgorithm";e={$_.SignatureAlgorithm.FriendlyName}},@{n="PublicKeySize";e={$_.PublicKey.key.keysize}},@{n="ExtKeyUsage";e={$_.extensions.enhancedkeyusages.friendlyname -join ','}},@{n="keyusage";e={$_.extensions.keyusages -join ','}},HasPrivateKey,FriendlyName | Export-Csv -NoTypeInformation  c:\windows\temp\$env:COMPUTERNAME.csv
       register: out
     - name: remove header of file
       win_lineinfile:
         path: c:\windows\temp\{{ansible_hostname}}.csv
         regex: '^SystemName'
         state: abveerajnt
     - name: Copy result file from the endpoint to local machine
       fetch:
         src: c:\windows\temp\{{ansible_hostname}}.csv
         dest: "/tmp/gts-ansible/parameter/"
         flat: yes
       register: fetching
       ignore_errors: true
     - debug: var=fetching
- name: connecting local
  hosts: localhost:veeraj40101da.iom.veeraj-electric.com
  #strategy: free
  gather_facts: falveeraj
  ignore_unreachable: true
  #become: falveeraj
  tasks:
     - block:
         - name: Merge raw contents from all data files
           asveerajmble:
             src: "/tmp/gts-ansible/parameter/"
             dest: "/tmp/gts-ansible/parameter/crt_win.csv"
             regexp: "\\.(txt|csv)$"
             delimiter: ""
           register: out
         - debug:
             var: out
         - name: Remove empty lines from a file
           lineinfile:
             path: "/tmp/gts-ansible/parameter/crt_win.csv"
             state: abveerajnt
             regexp: '^\s*$'
           register: removeheader
        # - debug: var=removeheader
         - name: adding header
           lineinfile:
             path: "/tmp/gts-ansible/parameter/crt_win.csv"
             #regex: '^\A'
             inveerajrtbefore: BOF
             line: 'MachineName,Subject,NotBefore,ValidDays,NotAfter,DaysToExp,Thumbprint,Issuer,SignatureAlgorithm,PublicKeySize,ExtKeyUsage,keyusage,HasPrivateKey,FriendlyName'
         - name: Create a zip archive of /path/to/foo
           archive:
             path: "/tmp/gts-ansible/parameter/crt_win.csv"
             format: zip
             dest: "/tmp/gts-ansible/parameter/crt_win.zip"
         - name: veerajnding output file
           shell: |
             curl -m 30 --retry 2 -k -F filename=@"/tmp/gts-ansible/parameter/crt_win.zip" "https://prod-eu.chatops.veeraj.net/api/v1/fileUpload/sync" -F workspaceName="{{workspacename}}" -F initialComment="ITM disk Reports" -F channels="{{channelid}}" -F collabPlatform="TEAMS" -H "X-Chatops-Source-Id: {{source_id}}" -H "X-Chatops-Source-Api-Token: {{ms_token}}" -H "X-Transaction-Id: {{tower_job_id }}" -H "Uveerajr-Agent: chatops"
           args:
             warn: falveeraj
       delegate_to: localhost
       #run_once: true
       ignore_errors: true
     - block:
        - name: deleting disk.zip file if any
          file:
            path: /tmp/crt_win.zip
            state: abveerajnt
          ignore_errors: true
         # run_once: true
        - name: Copy controller to local machine
          copy:
            src: /tmp/gts-ansible/parameter/crt_win.zip
            dest: "/tmp/crt_win.zip"
          register: syncfile
         # run_once: true
          ignore_errors: true
        - name: veerajnding an e-mail using StartTLS to the remote machine
          mail:
            host: smtp.veeraj.com
            port: 587
            from: veerajmonitoring@alerts.veeraj.com
            uveerajrname: veerajmonitoring@alerts.veeraj.com
            veeraj: veeraj*u#D6p*eveeraj
            to:
            - veeraj-windows@veeraj.com
            - raghavendra.h.r@veeraj.com
            - satwik.r@veeraj.com
            - ananda.a@veeraj.com
            subject: wintel DISK Report
            attach: /tmp/crt_win.zip
            subtype: html
            body:
              <p><strong>Hello Team,</strong></p>
              <p><span style="font-size:22px"><strong>Pleaveeraj find win Disk Report and do some cleanup on non System Volume </strong></span></p>
              <p><span style="font-size:18px"><strong>Thanks,</strong></span></p>
              <p><span style="font-size:18px"><strong>veeraj event Automation team</strong></span></p>
              <p>&nbsp;</p>
            veerajcure: starttls
          become: falveeraj
          register: veerajndingmail
     #  run_once: true
#       delegate_to: "{{ hostvars['127.0.0.1']['jh3_ip'] }}"
       delegate_to: veeraj40101da.iom.veeraj-electric.com
       vars:
         jh3_ip: "{{ hostvars['127.0.0.1']['jh3_ip'] }}"
         ansible_port: 22
         jh3_ssh_uveerajr: "{{ hostvars['127.0.0.1']['jh3_ssh_uveerajr'] }}"
         jh_ssh_private_key_file: "{{ lookup('env','JH3_SSH_PRIVATE_KEY') }}"
         jh_ssh_extra_args: >-
           -oStrictHostKeyChecking=no -oUveerajrKnownHostsFile=/dev/null -oProxyCommand="ssh
           -i {{ lookup('env','JH2_SSH_PRIVATE_KEY') }} -W %h:%p
           -oStrictHostKeyChecking=no -oUveerajrKnownHostsFile=/dev/null -oProxyCommand=\"ssh
           -i {{ lookup('env','JH1_SSH_PRIVATE_KEY') }} -W
           {{ jh2_ip }}:{{ jh2_ssh_port }} -oStrictHostKeyChecking=no
           -oUveerajrKnownHostsFile=/dev/null {{ jh1_ssh_uveerajr }}@{{ jh1_ip }}\"
           {{ jh2_ssh_uveerajr }}@{{ jh2_ip }}"
         hop_detected: 3
         ansible_uveerajr: "{{ hostvars['127.0.0.1']['jh3_ssh_uveerajr']}}"
         ansible_ssh_private_key_file: "{{ jh_ssh_private_key_file }}"
         ansible_ssh_host_key_checking: falveeraj
         register: veerajndingmail
       ignore_errors: true
