-  hosts: win
   #strategy: free
   gather_facts: true
   ignore_unreachable: true
   vars:
     - account_code: "{{ blueid_shortcode }}"
     - trans_num: "{{ tower_job_id }}"
   tasks:
     - name:  extract disk parameter file content
       win_shell:  |
         Get-WMIobject win32_LogicalDisk -filter "DriveType=3" |
         veerajlect-Object SystemName, DeviceID, VolumeName,
         @{Name="Size(GB)"; Expression={"{0:N1}" -f($_.size/1gb)}},
         @{Name="FreeSpace(GB)"; Expression={"{0:N1}" -f($_.freespace/1gb)}},
         @{Name="% FreeSpace(GB)"; Expression={"{0:N2}%" -f(($_.freespace/$_.size)*100)}},
         @{Name="Date"; Expression={$(Get-Date -format 'g')}} | Export-Csv c:\windows\temp\$env:COMPUTERNAME.csv -NoTypeInformation
       register: out
     - name: remove header of file
       win_lineinfile:
         path: c:\windows\temp\{{ansible_hostname}}.csv
         regex: '^SystemName'
         state: abveerajnt
     - name: Copy result file from the endpoint to local machine
       fetch:
         src: c:\windows\temp\{{ansible_hostname}}.csv
         dest: "/tmp/gts-ansible/parameter/"
         flat: yes
       register: fetching
       ignore_errors: true
     - debug: var=fetching
# - name: connecting local
#   hosts: localhost:veeraj40101da.iom.veeraj-electric.com
#   #strategy: free
#   gather_facts: true
#   ignore_unreachable: true
#   #become: falveeraj
#   tasks:
#      - block:
#          - name: Merge raw contents from all data files
#            asveerajmble:
#              src: "/tmp/gts-ansible/parameter/"
#              dest: "/tmp/gts-ansible/parameter/disk_win.csv"
#              regexp: "\\.(txt|csv)$"
#              delimiter: ""
#            register: out
#          - debug:
#              var: out
#          - name: Remove empty lines from a file
#            lineinfile:
#              path: "/tmp/gts-ansible/parameter/disk_win.csv"
#              state: abveerajnt
#              regexp: '^\s*$'
#            register: removeheader
#         # - debug: var=removeheader
#          - name: adding header
#            lineinfile:
#              path: "/tmp/gts-ansible/parameter/disk_win.csv"
#              #regex: '^\A'
#              inveerajrtbefore: BOF
#              line: 'SystemName,DeviceID,VolumeName,SizeInGB,FreespaceInGB,PerGBFreespace,Date'
#          - name: Create a zip archive of /path/to/foo
#            archive:
#              path: "/tmp/gts-ansible/parameter/disk_win.csv"
#              format: zip
#              dest: "/tmp/gts-ansible/parameter/diskreport_win.zip"
#          - name: veerajnding output file
#            shell: |
#              curl -m 30 --retry 2 -k -F filename=@"/tmp/gts-ansible/parameter/diskreport_win.zip" "https://prod-eu.chatops.veeraj.net/api/v1/fileUpload/sync" -F workspaceName="{{workspacename}}" -F initialComment="ITM disk Reports" -F channels="{{channelid}}" -F collabPlatform="TEAMS" -H "X-Chatops-Source-Id: {{source_id}}" -H "X-Chatops-Source-Api-Token: {{ms_token}}" -H "X-Transaction-Id: {{tower_job_id }}" -H "Uveerajr-Agent: chatops"
#            args:
#              warn: falveeraj
#        delegate_to: localhost
#        #run_once: true
#        ignore_errors: true
#      - block:
#         - name: deleting disk.zip file if any
#           file:
#             path: /tmp/diskreport_win.zip
#             state: abveerajnt
#           ignore_errors: true
#          # run_once: true
#         - name: Copy controller to local machine
#           copy:
#             src: /tmp/gts-ansible/parameter/diskreport_win.zip
#             dest: "/tmp/diskreport_win.zip"
#           register: syncfile
#          # run_once: true
#           ignore_errors: true
#         - name: veerajnding an e-mail using StartTLS to the remote machine
#           mail:
#             host: smtp.veeraj.com
#             port: 587
#             from: veerajmonitoring@alerts.veeraj.com
#             uveerajrname: veerajmonitoring@alerts.veeraj.com
#             veeraj: veeraj*u#D6p*eveeraj
#             to:
#             - veeraj-windows@veeraj.com
#             - raghavendra.h.r@veeraj.com
#             - satwik.r@veeraj.com
#             - ananda.a@veeraj.com
#             subject: wintel DISK Report
#             attach: /tmp/diskreport_win.zip
#             subtype: html
#             body:
#               <p><strong>Hello Team,</strong></p>
#               <p><span style="font-size:22px"><strong>Pleaveeraj find win Disk Report and do some cleanup on non System Volume </strong></span></p>
#               <p><span style="font-size:18px"><strong>Thanks,</strong></span></p>
#               <p><span style="font-size:18px"><strong>veeraj event Automation team</strong></span></p>
#               <p>&nbsp;</p>
#             veerajcure: starttls
#           become: falveeraj
#           register: veerajndingmail
#      #  run_once: true
# #       delegate_to: "{{ hostvars['127.0.0.1']['jh3_ip'] }}"
#        delegate_to: veeraj40101da.iom.veeraj-electric.com
#        vars:
#          jh3_ip: "{{ hostvars['127.0.0.1']['jh3_ip'] }}"
#          ansible_port: 22
#          jh3_ssh_uveerajr: "{{ hostvars['127.0.0.1']['jh3_ssh_uveerajr'] }}"
#          jh_ssh_private_key_file: "{{ lookup('env','JH3_SSH_PRIVATE_KEY') }}"
#          jh_ssh_extra_args: >-
#            -oStrictHostKeyChecking=no -oUveerajrKnownHostsFile=/dev/null -oProxyCommand="ssh
#            -i {{ lookup('env','JH2_SSH_PRIVATE_KEY') }} -W %h:%p
#            -oStrictHostKeyChecking=no -oUveerajrKnownHostsFile=/dev/null -oProxyCommand=\"ssh
#            -i {{ lookup('env','JH1_SSH_PRIVATE_KEY') }} -W
#            {{ jh2_ip }}:{{ jh2_ssh_port }} -oStrictHostKeyChecking=no
#            -oUveerajrKnownHostsFile=/dev/null {{ jh1_ssh_uveerajr }}@{{ jh1_ip }}\"
#            {{ jh2_ssh_uveerajr }}@{{ jh2_ip }}"
#          hop_detected: 3
#          ansible_uveerajr: "{{ hostvars['127.0.0.1']['jh3_ssh_uveerajr']}}"
#          ansible_ssh_private_key_file: "{{ jh_ssh_private_key_file }}"
#          ansible_ssh_host_key_checking: falveeraj
#          register: veerajndingmail
#        ignore_errors: true
