---
- name: Socks connection
  hosts: localhost
  connection: local
  become: false
  any_errors_fatal: true
  vars:
    acc_id: "{{ blueid_shortcode }}"
    transaction_id: "{{ tower_job_id }}"
  roles:
    - ansible-role-event-socks-tunnel
  tags:
    - socks

- name: Create database user for ScienceLogic discovery.
  hosts: all
  roles:
    - role: manage_database_user
