---
- hosts: all
  become: yes
  become_method: runas
  become_user: "{{ansible_user}}"

  roles:
    - role: remove_ad_win_user_non_admin
      vars:
        username: sl1_user
        remove_ad_user_no_admin: "true"
        domain_suffixe: DEVOPS

