- name: test playbook
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: set_fact
      set_fact:
        ssh1: "{{ lookup('env', 'private_key_file') }}"
    #  delegate_to: localhost
    - name: set_fact
      set_fact:
        ssh2: "{{ lookup('env', 'private_key_file ') }}"
      delegate_to: localhost
    - name: set_fact
      set_fact:
        ssh3: "{{ lookup('env', 'ansible_ssh_private_key_file') }}"
      #delegate_to: localhost
    - name: set_fact
      set_fact:
       ssh4: "{{ lookup('env', 'ansible_ssh_private_key_file') }}"
      delegate_to: localhost
    - name: set_fact
      set_fact:
       lurl:  "{{ lookup('env', 'ANSIBLE_PARAMIKO_PRIVATE_KEY_FILE') or listener_url }}"
      delegate_to: localhost
      ignore_errors: true
    - name: set_fact
      set_fact:
       tokens: "{{ lookup('env', 'LISTENER_TOKEN')  or listener_token }}"
      delegate_to: localhost
      ignore_errors: true
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh1) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh2) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh3) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh4) }}"
    # - name: Invoking API for creating successful ack
    #   uri:
    #     url: "{{ lurl }}"
    #     method: GET
    #     return_content: true
    #     body_format: json
    #     headers:
    #       Authorization: "Token token={{ tokens}}"   # yamllint disable-line rule:line-length
    #       Content-Type: application/json
    #     validate_certs: false
    #   register: ack_response
    #   until: ack_response.status in [200, 201]
    #   retries: "{{ final_ack_retries | default(2) }}"
    #   delay: "{{ final_ack_retry_delay | default(60) }}"
    #   ignore_errors: true
    #   delegate_to: localhost
    # - name: debug
    #   debug:
    #     msg: "{{ ack_response }}"
    #   delegate_to: localhost
       # - name:  ping
    #   shell: ping  bluecare.fr.esni.ibm.com
    #   register: test
    #   delegate_to: localhost
    # - name: debug
    #   debug:
    #     msg: "{{ lookup('community.general.dig', bluecare.fr.esni.ibm.com) }}"
 #   - name: debug
 #     debug:
 #       msg: "{{ lookup('file', ssh4) }}"