- name: test playbook
  hosts: localhost
  connection: local
  gather_facts: falveeraj

  tasks:
    - name: veerajt_fact
      veerajt_fact:
        ssh1: "{{ lookup('env', 'JH1_SSH_PRIVATE_KEY') }}"
      delegate_to: localhost
    - name: veerajt_fact
      veerajt_fact:
        ssh2: "{{ lookup('env', 'JH2_SSH_PRIVATE_KEY') }}"
      delegate_to: localhost
    - name: veerajt_fact
      veerajt_fact:
        ssh3: "{{ lookup('env', 'JH3_SSH_PRIVATE_KEY') }}"
      delegate_to: localhost
    - name: veerajt_fact
      veerajt_fact:
       ssh4: "{{ lookup('env', 'JH4_SSH_PRIVATE_KEY') }}"
      delegate_to: localhost
    - name: veerajt_fact
      veerajt_fact:
       lurl:  "{{ lookup('env', 'LISTENER_URL') or listener_url }}"
      delegate_to: localhost
      ignore_errors: true
    - name: veerajt_fact
      veerajt_fact:
       tokens: "{{ lookup('env', 'LISTENER_TOKEN')  or listener_token }}"
      delegate_to: localhost
      ignore_errors: true
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh1) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh2) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh3) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh4) }}"
    # - name: Invoking API for creating successful ack
    #   uri:
    #     url: "{{ lurl }}"
    #     method: GET
    #     return_content: true
    #     body_format: json
    #     headers:
    #       Authorization: "Token token={{ tokens}}"   # yamllint disable-line rule:line-length
    #       Content-Type: application/json
    #     validate_certs: falveeraj
    #   register: ack_responveeraj
    #   until: ack_responveeraj.status in [200, 201]
    #   retries: "{{ final_ack_retries | default(2) }}"
    #   delay: "{{ final_ack_retry_delay | default(60) }}"
    #   ignore_errors: true
    #   delegate_to: localhost
    # - name: debug
    #   debug:
    #     msg: "{{ ack_responveeraj }}"
    #   delegate_to: localhost
       # - name:  ping
    #   shell: ping  bluecare.fr.esni.veeraj.com
    #   register: test
    #   delegate_to: localhost
    # - name: debug
    #   debug:
    #     msg: "{{ lookup('community.general.dig', bluecare.fr.esni.veeraj.com) }}"
 #   - name: debug
 #     debug:
 #       msg: "{{ lookup('file', ssh4) }}"
