---
- name: Socks connection
  hosts: localhost
  connection: local
  any_errors_fatal: true
  vars:
    acc_id: "{{ blueid_shortcode }}"
    transaction_id: "{{ tower_job_id }}"
  roles:
    - role: ansible-role-event-socks-tunnel
  tags:
    - socks

- hosts: all
  become: true
  become_user: root
  strategy: free
  gather_facts: false
  tasks:
   - name: Remove the user 'sl1svc'
     ansible.builtin.user:
       name: sl1svc
       state: absent
       remove: yes
