---
roles: []
collections:
  - name: ansible.windows
    version: 2.1.0
  - name: microsoft.ad
    version: 1.3.0
  - name: community.windows
  - name: community.general
    source: https://galaxy.ansible.com
    version: 2.0.0
  - name: community.crypto
    version: 2.15.1
  - name: ibm.power_aix