---
- name: Generate a Self-signed Certificate
  block:
    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: "{{ winrm_path_certificate_key_in_localhost }}"
        size: 4096
      delegate_to: localhost

    - name: Generate an OpenSSL Certificate Signing Request for WinRM Certificate authentication
      community.crypto.openssl_csr:
        path: "{{ winrm_path_certificate_csr_in_localhost }}"
        privatekey_path: "{{ winrm_path_certificate_key_in_localhost }}"
        common_name: "{{ ansible_facts.hostname }}"
        extended_key_usage:
          - clientAuth
          - serverAuth
        key_usage:
          - digitalSignature
          - keyEncipherment
      delegate_to: localhost

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: "{{ winrm_path_certificate_in_localhost }}"
        privatekey_path: "{{ winrm_path_certificate_key_in_localhost }}"
        csr_path: "{{ winrm_path_certificate_csr_in_localhost }}"
        provider: selfsigned
      delegate_to: localhost

    - name: Generate PKCS#12 file
      community.crypto.openssl_pkcs12:
        action: export
        path: "{{ winrm_path_certificate_in_localhost_p12 }}"
        friendly_name: winrmcertificate
        privatekey_path: "{{ winrm_path_certificate_key_in_localhost }}"
        certificate_path: "{{ winrm_path_certificate_in_localhost }}"
        state: present
      delegate_to: localhost

    - name: Copy the certificate to the Windows machine
      ansible.windows.win_copy:
        src: "{{ winrm_path_certificate_in_localhost_p12 }}"
        dest: "{{ winrm_path_certificate_in_windows_server }}"

    - name: Import a certificate
      ansible.windows.win_certificate_store:
        path: "{{ winrm_path_certificate_in_windows_server }}"
        key_exportable: true
        key_storage: "machine"
        state: present
      register: certifimport

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ certifimport.thumbprints[0] }}"

    - name: Create Securised listener
      ansible.windows.win_shell: "New-Item WSMan:\\localhost\\Listener -Address * -Transport HTTPS -HostName \"{{ ansible_facts.hostname }}\"\
                                  -CertificateThumbPrint \"{{ certifimport.thumbprints[0] }}\"  -Force"

    - name: Remove local certificate files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ winrm_path_certificate_key_in_localhost }}"
        - "{{ winrm_path_certificate_in_localhost }}"
        - "{{ winrm_path_certificate_csr_in_localhost }}"
        - "{{ winrm_path_certificate_in_localhost_p12 }}"
      delegate_to: localhost

    - name: Report success
      ansible.builtin.include_role:
        name: returncode
      vars:
        # noqa var-naming[no-role-prefix]
        rc_success: true

  rescue:
    - name: Something in block failed. Generate error.
      ansible.builtin.include_role:
        name: returncode
      vars:
        # noqa var-naming[no-role-prefix]
        rc_support: developer
        rc_group: framework_playbook
        rc_number: 3001
        rc_message: "Failed to generate Self-signed Certificate"
