name: Send a request to documentation repository for documentation rebuild

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.md'
      - mkdocs.yml

jobs:
  mk-docs-event:
    runs-on: ubuntu-latest
    steps:
      - name: MK docs update event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.kyndryl.net/api/v3/repos/DevOps-automation-squad/documentation/dispatches \
            -d '{"event_type":"mk-docs-event","client_payload":{"unit":false,"integration":true}}'
